name: zerothreesix_dart
description: victor7w7r utils collection for dart.
version: 0.1.7

environment:
  sdk: ^3.5.0

dependencies:
  cli_menu: ^0.4.0+1
  console: ^4.1.0
  dart_console: ^4.1.0
  fpdart: ^1.1.0
  get_it: ^7.7.0

dependency_overrides:
  win32: 5.5.4

dev_dependencies:
  coverage: ^1.9.0
  custom_lint: ^0.6.4
  dart_code_linter: ^1.1.3
  import_sorter: ^4.6.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  pyramid_lint: ^2.0.0
  remove_from_coverage: ^2.0.0
  test: ^1.25.8

import_sorter:
  comments: false