name: zerothreesix_dart
description: victor7w7r utils collection for dart.
version: 0.1.2

environment:
  sdk: ^3.3.0

dependencies:
  console: ^4.1.0
  dart_console2: ^3.0.0
  fpdart: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
