name: zerothreesix_dart
description: victor7w7r utils collection for dart.
version: 0.1.5

environment:
  sdk: ^3.4.4

dependencies:
  cli_menu: ^0.4.0+1
  console: ^4.1.0
  dart_console2: ^3.1.1
  fpdart: ^1.1.0
  get_it: ^7.7.0

dev_dependencies:
  coverage: ^1.9.0
  custom_lint: ^0.6.4
  dart_code_linter: ^1.1.3
  import_sorter: ^4.6.0
  lints: ^4.0.0
  mocktail: ^1.0.4
  pyramid_lint: ^2.0.0
  remove_from_coverage: ^2.0.0
  test: ^1.25.7
  test_process: ^2.1.0

import_sorter:
  comments: false