name: zerothreesix_dart
description: victor7w7r utils collection for dart.
version: 0.0.3

environment:
  sdk: ^3.0.6

dependencies:
  console: ^4.1.0
  dcli: ^3.0.2
  fpdart: ^1.0.0

dev_dependencies:
  lints: ^2.1.1
